name: Daily Run

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Run script
      env:
        LANG: ${{ secrets.LANGUAGE }}
        USERNAME: ${{ github.repository_owner }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        KEY: ${{ secrets.OPENAI_KEY }}
      run: |
        cd src
        uv run main.py -y -r -u ${USERNAME} -t ${TOKEN} -k ${KEY} -l ${LANG}
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git status
        git commit -m "Update from daily run [skip ci]" || echo "No changes to commit"
        git push 